export const SEARCH_HISTORY_QUEUE_NAME = 'search-histories';

const SEARCH_HISTORY_QUEUE_SUFFIX = '_SEARCH_HISTORY_QUEUE';
const GET_TOP5 = 'GET_TOP5' + SEARCH_HISTORY_QUEUE_SUFFIX;
const INSERT = 'INSERT' + SEARCH_HISTORY_QUEUE_SUFFIX;

export default { GET_TOP5, INSERT };
